server:
  port: 8080
spring:
  datasource:
    dataSourceClassName: com.mysql.jbdc.jdbc2.optional.MysqlDataSource
    url: jdbc:mysql://localhost/gdg
    username: root
    password:

  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQLInnoDBDialect
      ddl-auto: update
      show_sql: true
      open-in-view: false